### ISSUE TITLE
Loading fiveam neccessary at defsystem-depends-on time

### ISSUE THREAD

**Issue by ghost** [rpgoldman/fiveam-asdf#3]
The :defsystem-depends-on should already load "fiveam", otherwise with `:class :fiveam-tester-system` ASDF doesn't know about fiveam and complains: The name "IT.BESE.FIVEAM" does not designate any package. This is irritating in the README.

**Comment by rpgoldman** [comment]
No, that is not necessary.   See, for example, the SHOP system, which loads quite happily without FiveAM loaded until you try to test the system.

*However*, it's ASDF's `:defsystem-depends-on` that is broken. You can't rely on it, and instead must put `(asdf:load-system "fiveam-asdf")` into your `.asd` file.

The reason is that ASDF cannot safely read a `defsystem` form for a `:fiveam-tester-system` without *already* having loaded "fiveam-asdf".  The reasons for this are too complex to go into here, but it's a problem with ASDF, not with this library.

**Comment by ghost** [comment]
ASDF `:defsystem-depends-on` is NOT broken, it just loads the systems on which the `defsystem` depends on prior to any other steps in order to define the new system (to avoid a non-complete and polluted building environment). Your library is referring to external symbols of Fiveam _before_ ASDF knows about Fiveam (and doing `(intern (symbol-name '#:run) :fiveam)` doesn't really help for this). Solutions are

- packing Fiveam in fiveam-asdf as a dependency and shipping them together as one package (perhaps proposing as a feature to the Fiveam itself!)
- using `asdf-user` package code.lisp since it is the current package when people are in their .asd files
- doing `:defsystem-depends-on ("fiveam" "fiveam-asdf")` in `defsystem` so the neccessary loading of fiveam happens in the right moment.

**Comment by rpgoldman** [comment]
Here is the transcript from loading the asdf file for SHOP3 (https://github.com/shop-planner/shop3/blob/master/shop3/shop3.asd):
```
CL-USER(1): (asdf:load-asd "shop3.asd")

; compiling file "/Users/rpg/lisp/fiveam-asdf/code.lisp" (written 15 APR 2019 10:08:45 PM):
; processing (IN-PACKAGE :ASDF)
; processing (DEFCLASS FIVEAM-TESTER-SYSTEM ...)
; processing (DEFINE-CONDITION FIVEAM-ASDF-FAILURE ...)
; processing (DEFINE-CONDITION FIVEAM-TEST-FAIL ...)
; processing (DEFINE-CONDITION FIVEAM-WRONG-NUMBER-OF-CHECKS ...)
; processing (DEFGENERIC TEST-PACKAGE ...)
; processing (DEFMETHOD PERFORM ...)
; processing (DEFMETHOD COMPONENT-DEPENDS-ON ...)
; processing (DEFMETHOD COMPONENT-DEPENDS-ON ...)
; processing (EXPORT (QUOTE FIVEAM-TESTER-SYSTEM) ...)

; wrote /Users/rpg/.cache/common-lisp/sbcl-2.0.8-macosx-x64/Users/rpg/lisp/fiveam-asdf/code-tmpAR3FSGEY.fasl
; compilation finished in 0:00:00.028
#<ASDF/FIND-SYSTEM:DEFINE-OP >
#<ASDF/PLAN:SEQUENTIAL-PLAN {10094B0D83}>
```

You will see that FiveAM is *not* loaded here, but that fiveam-asdf *is* loaded.  You will also see that fiveam-asdf is loaded by hand, and is not loaded by `:defsystem-depends-on`.

Now, here is the key piece of what goes wrong if I remove the hand loading, and rely only on `:defsystem-depends-on`:

```
ebugger invoked on a LOAD-SYSTEM-DEFINITION-ERROR in thread #<THREAD "main thread" RUNNING {10008B80E3}>: Error while trying to load definition for system shop3-defsystem-depends-on from pathname /Users/rpg/lisp/shop/shop3/shop3-defsystem-depends-on.asd: EXPORT FIVEAM-TESTER-SYSTEM causes name-conflicts in #<PACKAGE "SHOP-ASD"> between the following symbols: ASDF/INTERFACE::FIVEAM-TESTER-SYSTEM, SHOP-ASD::FIVEAM-TESTER-SYSTEM
See also:
  The ANSI Standard, Section 11.1.1.2.5

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [TRY-RECOMPILING              ] Recompile code and try loading it again
  1: [RETRY                        ] Retry loading FASL for #<CL-SOURCE-FILE "fiveam-asdf" "code">.
  2: [ACCEPT                       ] Continue, treating loading FASL for #<CL-SOURCE-FILE "fiveam-asdf" "code"> as having been successful.
  3: [RETRY                        ] Retry EVAL of current toplevel form.
  4: [CONTINUE                     ] Ignore error and continue loading file "/Users/rpg/lisp/shop/shop3/shop3-defsystem-depends-on.asd".
  5: [ABORT                        ] Abort loading file "/Users/rpg/lisp/shop/shop3/shop3-defsystem-depends-on.asd".
  6:                                 Retry #<DEFINE-OP > on #<UNDEFINED-SYSTEM "shop3-defsystem-depends-on">.
  7:                                 Continue, treating #<DEFINE-OP > on #<UNDEFINED-SYSTEM "shop3-defsystem-depends-on"> as having been successful.
  8:                                 Retry ASDF operation.
  9: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
 10:                                 Retry ASDF operation.
 11:                                 Retry ASDF operation after resetting the configuration.
 12:                                 Exit debugger, returning to top level.

(SB-EXT:NAME-CONFLICT #<PACKAGE "SHOP-ASD"> EXPORT FIVEAM-TESTER-SYSTEM FIVEAM-TESTER-SYSTEM SHOP-ASD::FIVEAM-TESTER-SYSTEM)
```

The problem is that when the defsystem is first parsed, the symbol `FIVEAM-TESTER-SYSTEM` is read into the package of the defsystem (here that is `shop-asd`, but elsewhere it could be `shop-user`).  That causes the loading of the system to fail, because when `fiveam-asdf` is loaded, there is a name conflict.  That is what I mean about `:defsystem-depends-on` being broken.

If you would like more details, look into the archives of the ASDF-devel mailing list: this is a known problem with `defsystem-depends-on`.
